### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by shanehull** [Macdeviant/Edumail-Reset#1]
Sorry if this is a dumb question, but I'm fairly new to scripting, specially on OSX.

Where do you place this, and how do you execute it?

I'm very interested, and if I can make it easy to execute for my staff that would be a saviour.

**Comment by Macdeviant** [comment]
Hi Shane, this needs to go into a web server with PHP turned on.
Line 65 in "index.php" needs to have the relative or complete pathe to "script.sh"

**Comment by shanehull** [comment]
Perfect, thanks mate!

**Comment by Macdeviant** [comment]
Just a quick note not to spread this around too much.

**Comment by shanehull** [comment]
No problem.
